function header = ImportHeaderTRC(filename, dataLines)
%IMPORTFILE Import data from a text file
% Auto-generated by MATLAB on 13-Feb-2024 13:32:34

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, 6];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 131);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Frame", "Time", "LFHD", "VarName4", "VarName5", "RFHD", "VarName7", "VarName8", "RBHD", "VarName10", "VarName11", "LBHD", "VarName13", "VarName14", "C7", "VarName16", "VarName17", "T10", "VarName19", "VarName20", "R10", "VarName22", "VarName23", "CLAV", "VarName25", "VarName26", "STRN", "VarName28", "VarName29", "LSHO", "VarName31", "VarName32", "LUPA", "VarName34", "VarName35", "LELB", "VarName37", "VarName38", "LFRA", "VarName40", "VarName41", "LWRA", "VarName43", "VarName44", "LWRB", "VarName46", "VarName47", "LFIN0", "VarName49", "VarName50", "LFINx", "VarName52", "VarName53", "LFINy", "VarName55", "VarName56", "RSHO", "VarName58", "VarName59", "RUPA", "VarName61", "VarName62", "RELB", "VarName64", "VarName65", "RFRA", "VarName67", "VarName68", "RWRA", "VarName70", "VarName71", "RWRB", "VarName73", "VarName74", "RFIN0", "VarName76", "VarName77", "RFINx", "VarName79", "VarName80", "RFINy", "VarName82", "VarName83", "LASI", "VarName85", "VarName86", "RASI", "VarName88", "VarName89", "RBSI", "VarName91", "VarName92", "LBSI", "VarName94", "VarName95", "LTHI", "VarName97", "VarName98", "LKNE", "VarName100", "VarName101", "LTIB", "VarName103", "VarName104", "LANK", "VarName106", "VarName107", "LHEE", "VarName109", "VarName110", "LTOE", "VarName112", "VarName113", "RTHI", "VarName115", "VarName116", "RKNE", "VarName118", "VarName119", "RTIB", "VarName121", "VarName122", "RANK", "VarName124", "VarName125", "RHEE", "VarName127", "VarName128", "RTOE", "VarName130", "VarName131"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Frame", "Time", "LFHD", "VarName4", "VarName5", "RFHD", "VarName7", "VarName8", "RBHD", "VarName10", "VarName11", "LBHD", "VarName13", "VarName14", "C7", "VarName16", "VarName17", "T10", "VarName19", "VarName20", "R10", "VarName22", "VarName23", "CLAV", "VarName25", "VarName26", "STRN", "VarName28", "VarName29", "LSHO", "VarName31", "VarName32", "LUPA", "VarName34", "VarName35", "LELB", "VarName37", "VarName38", "LFRA", "VarName40", "VarName41", "LWRA", "VarName43", "VarName44", "LWRB", "VarName46", "VarName47", "LFIN0", "VarName49", "VarName50", "LFINx", "VarName52", "VarName53", "LFINy", "VarName55", "VarName56", "RSHO", "VarName58", "VarName59", "RUPA", "VarName61", "VarName62", "RELB", "VarName64", "VarName65", "RFRA", "VarName67", "VarName68", "RWRA", "VarName70", "VarName71", "RWRB", "VarName73", "VarName74", "RFIN0", "VarName76", "VarName77", "RFINx", "VarName79", "VarName80", "RFINy", "VarName82", "VarName83", "LASI", "VarName85", "VarName86", "RASI", "VarName88", "VarName89", "RBSI", "VarName91", "VarName92", "LBSI", "VarName94", "VarName95", "LTHI", "VarName97", "VarName98", "LKNE", "VarName100", "VarName101", "LTIB", "VarName103", "VarName104", "LANK", "VarName106", "VarName107", "LHEE", "VarName109", "VarName110", "LTOE", "VarName112", "VarName113", "RTHI", "VarName115", "VarName116", "RKNE", "VarName118", "VarName119", "RTIB", "VarName121", "VarName122", "RANK", "VarName124", "VarName125", "RHEE", "VarName127", "VarName128", "RTOE", "VarName130", "VarName131"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Frame", "Time", "LFHD", "VarName4", "VarName5", "RFHD", "VarName7", "VarName8", "RBHD", "VarName10", "VarName11", "LBHD", "VarName13", "VarName14", "C7", "VarName16", "VarName17", "T10", "VarName19", "VarName20", "R10", "VarName22", "VarName23", "CLAV", "VarName25", "VarName26", "STRN", "VarName28", "VarName29", "LSHO", "VarName31", "VarName32", "LUPA", "VarName34", "VarName35", "LELB", "VarName37", "VarName38", "LFRA", "VarName40", "VarName41", "LWRA", "VarName43", "VarName44", "LWRB", "VarName46", "VarName47", "LFIN0", "VarName49", "VarName50", "LFINx", "VarName52", "VarName53", "LFINy", "VarName55", "VarName56", "RSHO", "VarName58", "VarName59", "RUPA", "VarName61", "VarName62", "RELB", "VarName64", "VarName65", "RFRA", "VarName67", "VarName68", "RWRA", "VarName70", "VarName71", "RWRB", "VarName73", "VarName74", "RFIN0", "VarName76", "VarName77", "RFINx", "VarName79", "VarName80", "RFINy", "VarName82", "VarName83", "LASI", "VarName85", "VarName86", "RASI", "VarName88", "VarName89", "RBSI", "VarName91", "VarName92", "LBSI", "VarName94", "VarName95", "LTHI", "VarName97", "VarName98", "LKNE", "VarName100", "VarName101", "LTIB", "VarName103", "VarName104", "LANK", "VarName106", "VarName107", "LHEE", "VarName109", "VarName110", "LTOE", "VarName112", "VarName113", "RTHI", "VarName115", "VarName116", "RKNE", "VarName118", "VarName119", "RTIB", "VarName121", "VarName122", "RANK", "VarName124", "VarName125", "RHEE", "VarName127", "VarName128", "RTOE", "VarName130", "VarName131"], "EmptyFieldRule", "auto");

% Import the data
header = readmatrix(filename, opts);

end
